language: python
python: 3.8

before_install:
  - sudo apt-get update
  - sudo apt-get install python3
  - sudo apt-get install python-pip
  - pip install pytest
  - pip install coverage
  
script:
   - python3 -ms pytest
   - coverage run -m pyte st
   - coverage report 2>&1 

after_success:
  - pip install coveralls
  - coveralls
